### PR TITLE
fix for sardana 3.0.3 in TangoAttrCTCtrl.py and tests for pep8

### PR DESCRIPTION
**Pull request by jkotan**
Hi,

we have tested TangoAttrCTCtrl with sardana 3.0.3 and it turns out we get an error without a second parameter (values) of StartOne command. 
I've also add flake8 tests in travis for pep8 and apply necessary corrections.

### CODE REVIEW

**Comment by jkotan** [comment]
I've moved flake8 travis tests to the github workflow action (it looks like actions for the repository are disable).

**Review by reszelaz — APPROVED** [review]
Thanks for the PR and patience in waiting for the review.

It looks OK to me, I just realized that when reviewing #1 I wrongly accepted change from `StartOneCT(self, axis)` to `StartOne(self, axis)`. Thanks for the correction.

I think rest of the changes from the PR are PEP8 and adding the flake8 check with GH actions, right? This is a great addition!

I have not tried these controllers but looks ok to me to merge.

**Comment by reszelaz** [comment]
Now I reviewed also the history of commits, and it looks like not related commits were included in the PR. They do not change the codebase, so not really problematic, but for the future please try to avoid them so it will be easier to review the history if necessary.

**Comment by jkotan** [comment]
Yes. Sorry, I've created the PR from my forked repo (removing staff we use only at DESY e.g. setup.py).

**Comment by reszelaz** [comment]
Having a setup.py would also help in this project:)

**Pull request merged**
